# Form implementation generated from reading ui file 'ANP.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_import = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_import.setGeometry(QtCore.QRect(11, 11, 141, 23))
        self.pushButton_import.setObjectName("pushButton_import")
        self.table1 = QtWidgets.QTableView(parent=self.centralwidget)
        self.table1.setGeometry(QtCore.QRect(11, 41, 131, 81))
        self.table1.setObjectName("table1")
        self.table2 = QtWidgets.QTableView(parent=self.centralwidget)
        self.table2.setGeometry(QtCore.QRect(10, 390, 121, 81))
        self.table2.setObjectName("table2")
        self.table3 = QtWidgets.QTableView(parent=self.centralwidget)
        self.table3.setGeometry(QtCore.QRect(10, 510, 121, 81))
        self.table3.setObjectName("table3")
        self.table4 = QtWidgets.QTableView(parent=self.centralwidget)
        self.table4.setGeometry(QtCore.QRect(10, 630, 121, 81))
        self.table4.setObjectName("table4")
        self.graph_layout = QtWidgets.QWidget(parent=self.centralwidget)
        self.graph_layout.setGeometry(QtCore.QRect(620, 40, 841, 621))
        self.graph_layout.setObjectName("graph_layout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analyse Nébuleuse Planétaire"))
        self.pushButton_import.setText(_translate("MainWindow", "Import de données"))
