# Form implementation generated from reading ui file 'ANP.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph_layout = QtWidgets.QWidget(parent=self.centralwidget)
        self.graph_layout.setGeometry(QtCore.QRect(470, 40, 1031, 661))
        self.graph_layout.setObjectName("graph_layout")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 257, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_import1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_import1.setObjectName("pushButton_import1")
        self.horizontalLayout.addWidget(self.pushButton_import1)
        self.pushButton_import2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_import2.setObjectName("pushButton_import2")
        self.horizontalLayout.addWidget(self.pushButton_import2)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 41, 441, 741))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table1 = QtWidgets.QTableView(parent=self.widget)
        self.table1.setObjectName("table1")
        self.verticalLayout.addWidget(self.table1)
        self.table2 = QtWidgets.QTableView(parent=self.widget)
        self.table2.setObjectName("table2")
        self.verticalLayout.addWidget(self.table2)
        self.table3 = QtWidgets.QTableView(parent=self.widget)
        self.table3.setObjectName("table3")
        self.verticalLayout.addWidget(self.table3)
        self.table4 = QtWidgets.QTableView(parent=self.widget)
        self.table4.setObjectName("table4")
        self.verticalLayout.addWidget(self.table4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analyse Nébuleuse Planétaire"))
        self.pushButton_import1.setText(_translate("MainWindow", "Import de données1"))
        self.pushButton_import2.setText(_translate("MainWindow", "Import de données2"))
